Updated ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -18,16 +18,16 @@ jobs:
       - name: Run tests
         run: mvn test
     
-      - name: Verify OpenAPI docs
-        run: |
-          echo "Checking for OpenAPI spec"
+      #- name: Verify OpenAPI docs
+       # run: |
+        #  echo "Checking for OpenAPI spec"
           # Check both possible locations
-          if [ ! -f "target/classes/META-INF/openapi.json" ] && [ ! -f "target/classes/static/docs/openapi.json" ]; then
-            echo "::error::OpenAPI spec not found!"
-            exit 1
-          else
-            echo "OpenAPI spec found"
-          fi
+         # if [ ! -f "target/classes/META-INF/openapi.json" ] && [ ! -f "target/classes/static/docs/openapi.json" ]; then
+          #  echo "::error::OpenAPI spec not found!"
+           # exit 1
+          #else
+           # echo "OpenAPI spec found"
+          #fi
         
       - name: Upload Artifacts
         if: success()
